---

spring:
  r2dbc:
    url: r2dbc:h2:file:///./frequency-analyzer.db;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    username: sa
    password:
  liquibase:
    enabled: true
    url: jdbc:h2:file:./frequency-analyzer.db;
    user: sa
    password:
    change-log: classpath://db/changelog/changelog-master.yml
    driver-class-name: org.h2.Driver
